variables:
  IMAGE_NAME: nodirshox/px_backend
  IMAGE_TAG: latest

stages:
  - build
  - deploy

build_image:
  stage: build
  only:
    - main
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - chmod 700 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USERNAME@$SERVER_IP "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
      cd /home/ubuntu/px_devops/services &&
      docker compose down &&
      docker rmi $IMAGE_NAME:$IMAGE_TAG &&
      docker pull $IMAGE_NAME:$IMAGE_TAG &&
      docker compose up -d"
