package com.example.ppxprojextnew.Companent;

public enum Permission {
    ADD_ROLE, EDIT_ROLE, DELETE_ROLE, READ_ROLE,
    ADD_USER, EDIT_USER, DELETE_USER, READ_USER,
    ADD_STATEMENT, EDIT_STATEMENT, DELETE_STATEMENT, READ_STATEMENT,
    ADD_GUARDS, EDIT_GUARDS, DELETE_GUARDS, READ_GUARDS,
    ADD_WANTED, EDIT_WANTED, DELETE_WANTED, READ_WANTED,
    ADD_MISSING, EDIT_MISSING, DELETE_MISSING, READ_MISSING,
    ADD_WEAPONS, EDIT_WEAPONS, DELETE_WEAPONS, READ_WEAPONS,
    ADD_PERSONS, EDIT_PERSONS, DELETE_PERSONS, READ_PERSONS,
    ADD_PROF, EDIT_PROF, DELETE_PROF, READ_PROF,

}
